spring:
  datasource:
    url: jdbc:postgresql://10.140.0.5:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.140.0.6
    username: guest
    password: guest
    port: 5672